# config/settings.py

BASE_URL = "https://demoqa.com"
DEFAULT_ZOOM = "50%"
NOME_USUARIO = "BRUNO"
SOBRENOME_USUARIO = "LIMA"
EMAIL_USUARIO = "bruno.lima@example.com"
CURRENT_ADDRESS = "123 Main St, Anytown, USA"
PERMANENT_ADDRESS = "456 Elm St, Othertown, USA"
IDADE_USUARIO = "1"
SALARIO_USUARIO = "1234"
DEPARTAMENTO_USUARIO = "TI"
