name: Run Playwright Tests

on:
  workflow_dispatch:
    inputs:
      user:
        description: "Usuário do sistema"
        required: true
        default: "admin"

      password:
        description: "Senha do sistema"
        required: true
        default: "123456"

      browser:
        description: "Escolha o navegador"
        required: true
        type: choice
        options:
          - chromium
          - firefox
          - webkit
        default: chromium

jobs:
  tests:
    runs-on: ubuntu-latest

    env:
      USER: ${{ github.event.inputs.user }}
      PASSWORD: ${{ github.event.inputs.password }}
      NAVEGADOR: ${{ github.event.inputs.browser }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install

      - name: Run tests
        run: pytest